# Generated by Django 4.0.3 on 2022-05-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoEmpleadorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('logo', models.URLField(max_length=1000)),
            ],
            options={
                'db_table': 'Empleador',
            },
        ),
    ]
