# Generated by Django 4.0.3 on 2022-07-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoEmpleadorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('logo', models.URLField(blank=True, default='null', max_length=1000)),
            ],
        ),
    ]
