# Generated by Django 4.0.3 on 2022-05-11 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoempleadormodel',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empresa_id'),
        ),
        migrations.AlterField(
            model_name='infoempleadormodel',
            name='logo',
            field=models.URLField(max_length=1000),
        ),
    ]
