# Generated by Django 4.0.3 on 2022-07-07 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoempleadormodel',
            name='user_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empresa_id'),
        ),
    ]
