# Generated by Django 4.0.3 on 2022-06-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleador', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoempleadormodel',
            name='logo',
            field=models.URLField(default='null', max_length=1000),
        ),
        migrations.AlterModelTable(
            name='infoempleadormodel',
            table=None,
        ),
    ]
