# Generated by Django 4.0.3 on 2022-06-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleador', '0003_alter_infoempleadormodel_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoempleadormodel',
            old_name='User',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='infoempleadormodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
