# Generated by Django 4.0.3 on 2022-06-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleador', '0004_rename_user_infoempleadormodel_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoempleadormodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
