GENDER = [
    ('FEMENINO', 'FEMENINO'),
    ('MASCULINO','MASCULINO'),
    ('OTRO', 'OTRO')
]

MARITAL = [
    ('SOLTERO','SOLTERO'),
    ('CASADO','CASADO'),
    ('OTRO','OTRO')
]

NIVEL = [
    ('CARRERA TECNICA', 'CARRERA TECNICA'),
    ('UNIVERSIDAD', 'UNIVERSIDAD'),
    ('MAESTRIA', 'MAESTRIA'),
    ('DOCTORADO', 'DOCTORADO'),
    ('DIPLOMADO', 'DIPLOMADO'),
    ('CURSO', 'CURSO'),
    ('CERTIFICACION', 'CERTIFICACION'),
    ('OTRO', 'OTRO')
]

ESTATUS = [
    ('FINALIZADO', 'FINALIZADO'),
    ('EN CURSO', 'EN CURSO'),
    ('TRUNCO', 'TRUNCO'),
    ('OTRO', 'OTRO')
]


        