# Generated by Django 4.0.3 on 2022-07-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_acceso',
            field=models.CharField(max_length=200),
        ),
    ]
