# Generated by Django 4.0.3 on 2022-07-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_acceso',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
