# Generated by Django 4.0.3 on 2022-05-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intentos',
            field=models.IntegerField(default=0),
        ),
    ]
