# Generated by Django 4.0.3 on 2022-07-16 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postulaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postula',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postula',
            name='vacante_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vacantes.vacantesmodel'),
        ),
    ]
