# Generated by Django 4.0.3 on 2022-07-07 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacantesModel',
            fields=[
                ('vacante_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(max_length=500)),
                ('requisitos', models.TextField(max_length=300)),
                ('localidad', models.CharField(default='No aplica', max_length=30)),
                ('vacante_video', models.CharField(max_length=150)),
                ('sueldo', models.DecimalField(decimal_places=2, default='0.0', max_digits=30)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrido', 'Hibrido'), ('sin_especificar', 'Sin especificar')], max_length=20)),
                ('tipo_trabajo', models.CharField(choices=[('tiempo_completo', 'Tiempo completo'), ('medio_tiempo', 'Medio tiempo'), ('proyecto', 'Proyecto'), ('sin_especificar', 'Sin especificar')], max_length=20)),
                ('estado', models.CharField(choices=[('Aguascalientes', 'AGUASCALIENTES'), ('Baja California', 'BAJA_CALIFORNIA'), ('Baja California Sur', 'BAJA_CALIFORNIA_SUR'), ('Campeche', 'CAMPECHE'), ('Chiapas', 'CHIAPAS'), ('Chihuahua', 'CHIHUAHUA'), ('Ciudad de México', 'CD_MEX'), ('Coahuila', 'COAHUILA'), ('Colima', 'COLIMA'), ('Durango', 'DURANGO'), ('Guanajuato', 'GUANAJUATO'), ('Guerrero', 'GUERRERO'), ('Hidalgo', 'HIDALGO'), ('Jalisco', 'JALISCO'), ('Estado de México', 'EDO_MEX'), ('Michoacán', 'MICHOACAN'), ('Morelos', 'MORELOS'), ('Nayarit', 'NAYARIT'), ('Nuevo León', 'NUEVO_LEON'), ('Oaxaca', 'OAXACA'), ('Puebla', 'PUEBLA'), ('Querétaro', 'QUERETARO'), ('Quintana Roo', 'QUINTANA_ROO'), ('San Luis Potosí', 'SAN_LUIS_POTOSI'), ('Sinaloa', 'SINALOA'), ('Sonora', 'SONORA'), ('Tabasco', 'TABASCO'), ('Tamaulipas', 'TAMAULIPAS'), ('Tlaxcala', 'TLAXCALA'), ('Veracruz', 'VERACRUZ'), ('Yucatán', 'YUCATAN'), ('Zacatecas', 'ZACATECAS')], max_length=25)),
                ('area', models.CharField(choices=[('marketing', 'Marketing'), ('ventas', 'Ventas'), ('humanidades', 'Humanidades'), ('administración', 'Administración'), ('industria', 'Industria'), ('analisis de Datos', 'Analista de Datos'), ('tecnología', 'Tecnología'), ('desarrollo_software', 'Desarrollo de Software'), ('ciencias_exactas', 'Ciencias Exactas')], max_length=60)),
            ],
            options={
                'db_table': 'Vacantes',
            },
        ),
        migrations.CreateModel(
            name='PreguntasModel',
            fields=[
                ('preguntas_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('pregunta1', models.CharField(max_length=150)),
                ('pregunta2', models.CharField(max_length=150)),
                ('pregunta3', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('vacante_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacantes.vacantesmodel')),
            ],
            options={
                'db_table': 'Preguntas para Vacantes',
            },
        ),
    ]
