# Generated by Django 4.0.3 on 2022-05-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesmodel',
            name='date_birth',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
