# Generated by Django 4.0.3 on 2022-05-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPesonalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('paternal_lastname', models.CharField(max_length=30)),
                ('maternal_lastname', models.CharField(max_length=30)),
                ('date_birth', models.DateField(default='2018-06-29', null=True)),
                ('additional_mail', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino'), ('otro', 'Otro'), ('sin especificar', 'Sinespecificar')], default='sin especificar', max_length=20)),
                ('marital_status', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('otro', 'Otro'), ('sin especificar', 'Sinespecificar')], default='sin especificar', max_length=20)),
            ],
        ),
    ]
