# Generated by Django 4.0.3 on 2022-06-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interesesareasmodel',
            name='areas_id',
        ),
        migrations.RemoveField(
            model_name='rolareasmodel',
            name='interesesareas_id',
        ),
        migrations.RemoveField(
            model_name='rolareasmodel',
            name='rol_id',
        ),
        migrations.RemoveField(
            model_name='rolvacantesmodel',
            name='rol_id',
        ),
        migrations.RemoveField(
            model_name='rolvacantesmodel',
            name='vacantesareas_id',
        ),
        migrations.RemoveField(
            model_name='vacantesareasmodel',
            name='areas_id',
        ),
        migrations.RemoveField(
            model_name='vacantesareasmodel',
            name='vacante_id',
        ),
        migrations.RenameField(
            model_name='vacantesmodel',
            old_name='empleador_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='vacantesmodel',
            name='area_id',
        ),
        migrations.RemoveField(
            model_name='vacantesmodel',
            name='roles_id',
        ),
        migrations.AddField(
            model_name='vacantesmodel',
            name='area',
            field=models.CharField(choices=[('MARKETING', 'Marketing'), ('VENTAS', 'Ventas'), ('HUMANIDADES', 'Humanidades'), ('ADMINISTRACION', 'Administración'), ('INDUSTRIA', 'Industria'), ('ANALISTA', 'Analista de Datos'), ('TECNOLOGIA', 'Tecnología'), ('DESARROLLO', 'Desarrollo de Software'), ('CIENCIASEXACTAS', 'Ciencias Exactas')], default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacantesmodel',
            name='estado',
            field=models.CharField(choices=[('AGUASCALIENTES', 'Aguascalientes'), ('BAJA_CALIFORNIA', 'Baja California'), ('BAJA_CALIFORNIA_SUR', 'Baja California Sur'), ('CAMPECHE', 'Campeche'), ('CHIAPAS', 'Chiapas'), ('CHIHUAHUA', 'Chihuahua'), ('CD_MEX', 'Ciudad de México'), ('COAHUILA', 'Coahuila'), ('COLIMA', 'Colima'), ('DURANGO', 'Durango'), ('GUANAJUATO', 'Guanajuato'), ('GUERRERO', 'Guerrero'), ('HIDALGO', 'Hidalgo'), ('JALISCO', 'Jalisco'), ('EDO_MEX', 'Estado de México'), ('MICHOACAN', 'Michoacán'), ('MORELOS', 'Morelos'), ('NAYARIT', 'Nayarit'), ('NUEVO_LEON', 'Nuevo León'), ('OAXACA', 'Oaxaca'), ('PUEBLA', 'Puebla'), ('QUERETARO', 'Querétaro'), ('QUINTANA_ROO', 'Quintana Roo'), ('SAN_LUIS_POTOSI', 'San Luis Potosí'), ('SINALOA', 'Sinaloa'), ('SONORA', 'Sonora'), ('TABASCO', 'Tabasco'), ('TAMAULIPAS', 'Tamaulipas'), ('TLAXCALA', 'Tlaxcala'), ('VERACRUZ', 'Veracruz'), ('YUCATAN', 'Yucatán'), ('ZACATECAS', 'Zacatecas')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacantesmodel',
            name='experiencia',
            field=models.CharField(choices=[('INEXPERTO', 'Becario'), ('PASANTE', 'Pasante'), ('POCA', 'Poca Experiencia'), ('MEDIO', 'Experiencia Media'), ('ALTO', 'Mucha experiencia'), ('EXPERTO', 'Cargos ejecutivos')], default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preguntasmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vacantesmodel',
            name='localidad',
            field=models.CharField(default='No aplica', max_length=30),
        ),
        migrations.AlterField(
            model_name='vacantesmodel',
            name='modalidad',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('HIBRIDO', 'Hibrido')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vacantesmodel',
            name='tipo_trabajo',
            field=models.CharField(choices=[('TIEMPO_COMPLETO', 'Tiempo Completo'), ('MEDIO_TIEMPO', 'Medio Tiempo'), ('PROYECTO', 'Proyecto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vacantesmodel',
            name='vacante_video',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='AreasModel',
        ),
        migrations.DeleteModel(
            name='InteresesAreasModel',
        ),
        migrations.DeleteModel(
            name='RolAreasModel',
        ),
        migrations.DeleteModel(
            name='RolesModel',
        ),
        migrations.DeleteModel(
            name='RolVacantesModel',
        ),
        migrations.DeleteModel(
            name='VacantesAreasModel',
        ),
    ]
