# Generated by Django 4.0.3 on 2022-05-07 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntasmodel',
            name='status',
        ),
    ]
