# Generated by Django 4.0.3 on 2022-06-09 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoPesonalModel',
        ),
        migrations.RemoveField(
            model_name='rolesmodel',
            name='date_birth',
        ),
        migrations.AddField(
            model_name='preguntasmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacantesmodel',
            name='area_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacantes.areasmodel'),
        ),
        migrations.AlterField(
            model_name='vacantesmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacantesmodel',
            name='roles_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacantes.rolesmodel'),
        ),
        migrations.AlterField(
            model_name='vacantesmodel',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
