# Generated by Django 4.0.3 on 2022-07-07 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacantesmodel',
            name='estado',
            field=models.CharField(choices=[('Aguascalientes', 'AGUASCALIENTES'), ('Baja California', 'BAJA CALIFORNIA'), ('Baja California Sur', 'BAJA CALIFORNIA SUR'), ('Campeche', 'CAMPECHE'), ('Chiapas', 'CHIAPAS'), ('Chihuahua', 'CHIHUAHUA'), ('Ciudad de México', 'CD_MEX'), ('Coahuila', 'COAHUILA'), ('Colima', 'COLIMA'), ('Durango', 'DURANGO'), ('Guanajuato', 'GUANAJUATO'), ('Guerrero', 'GUERRERO'), ('Hidalgo', 'HIDALGO'), ('Jalisco', 'JALISCO'), ('Estado de México', 'EDO_MEX'), ('Michoacán', 'MICHOACAN'), ('Morelos', 'MORELOS'), ('Nayarit', 'NAYARIT'), ('Nuevo León', 'NUEVO LEON'), ('Oaxaca', 'OAXACA'), ('Puebla', 'PUEBLA'), ('Querétaro', 'QUERETARO'), ('Quintana Roo', 'QUINTANA ROO'), ('San Luis Potosí', 'SAN LUIS POTOSI'), ('Sinaloa', 'SINALOA'), ('Sonora', 'SONORA'), ('Tabasco', 'TABASCO'), ('Tamaulipas', 'TAMAULIPAS'), ('Tlaxcala', 'TLAXCALA'), ('Veracruz', 'VERACRUZ'), ('Yucatán', 'YUCATAN'), ('Zacatecas', 'ZACATECAS')], max_length=25),
        ),
        migrations.AlterField(
            model_name='vacantesmodel',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empresa'),
        ),
    ]
