# Generated by Django 4.0.3 on 2022-05-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0002_remove_preguntasmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacantesmodel',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=30),
        ),
        migrations.AlterModelTable(
            name='vacantesmodel',
            table=None,
        ),
    ]
