# Generated by Django 4.0.3 on 2022-06-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0002_remove_interesesareasmodel_areas_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacantesmodel',
            name='area',
        ),
        migrations.RemoveField(
            model_name='vacantesmodel',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='vacantesmodel',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='vacantesmodel',
            name='modalidad',
        ),
    ]
