# Generated by Django 4.0.3 on 2022-05-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0002_rolesmodel_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesmodel',
            name='date_birth',
            field=models.DateField(auto_now=True),
        ),
    ]
