# Generated by Django 4.0.3 on 2022-07-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0003_alter_vacantesmodel_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacantesmodel',
            name='localidad',
        ),
    ]
