# Generated by Django 4.0.3 on 2022-06-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0003_remove_vacantesmodel_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacantesmodel',
            name='tipo_trabajo',
            field=models.CharField(choices=[('TIEMPO_COMPLETO', 'Tiempo Completo'), ('MEDIO_TIEMPO', 'Medio Tiempo'), ('PROYECTO', 'Proyecto')], max_length=30),
        ),
    ]
