# Generated by Django 4.0.3 on 2022-05-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0003_alter_vacantesmodel_sueldo_alter_vacantesmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='preguntasmodel',
            table=None,
        ),
    ]
