# Generated by Django 4.0.3 on 2022-06-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0005_alter_vacantesmodel_tipo_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantesmodel',
            name='estado',
            field=models.CharField(choices=[('Aguascalientes', 'AGUASCALIENTES'), ('Baja California', 'BAJA_CALIFORNIA'), ('Baja California Sur', 'BAJA_CALIFORNIA_SUR'), ('Campeche', 'CAMPECHE'), ('Chiapas', 'CHIAPAS'), ('Chihuahua', 'CHIHUAHUA'), ('Ciudad de México', 'CD_MEX'), ('Coahuila', 'COAHUILA'), ('Colima', 'COLIMA'), ('Durango', 'DURANGO'), ('Guanajuato', 'GUANAJUATO'), ('Guerrero', 'GUERRERO'), ('Hidalgo', 'HIDALGO'), ('Jalisco', 'JALISCO'), ('Estado de México', 'EDO_MEX'), ('Michoacán', 'MICHOACAN'), ('Morelos', 'MORELOS'), ('Nayarit', 'NAYARIT'), ('Nuevo León', 'NUEVO_LEON'), ('Oaxaca', 'OAXACA'), ('Puebla', 'PUEBLA'), ('Querétaro', 'QUERETARO'), ('Quintana Roo', 'QUINTANA_ROO'), ('San Luis Potosí', 'SAN_LUIS_POTOSI'), ('Sinaloa', 'SINALOA'), ('Sonora', 'SONORA'), ('Tabasco', 'TABASCO'), ('Tamaulipas', 'TAMAULIPAS'), ('Tlaxcala', 'TLAXCALA'), ('Veracruz', 'VERACRUZ'), ('Yucatán', 'YUCATAN'), ('Zacatecas', 'ZACATECAS')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacantesmodel',
            name='modalidad',
            field=models.CharField(choices=[('Presencial', 'PRESENCIAL'), ('Virtual', 'VIRTUAL'), ('Hibrido', 'HIBRIDO'), ('Sin especificar', 'SIN_ESPECIFICAR')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacantesmodel',
            name='tipo_trabajo',
            field=models.CharField(choices=[('Tiempo Completo', 'COMPLETO'), ('Medio Tiempo', 'MEDIO'), ('Proyecto', 'PROYECTO'), ('Sin especificar', 'SIN_ESPECIFICAR')], max_length=30),
        ),
    ]
