# Generated by Django 4.0.3 on 2022-07-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoacademicamodel',
            name='estatus_academico',
            field=models.CharField(choices=[('Finalizado', 'Finalizado'), ('En Curso', 'En Curso'), ('Trunco', 'Trunco'), ('Otro', 'Otro')], default='sin especificar', max_length=20),
        ),
        migrations.AlterField(
            model_name='infoacademicamodel',
            name='nivel_escolar',
            field=models.CharField(choices=[('Carrera tecnica', 'Carrera tecnica'), ('Universidad', 'Universidad'), ('Maestria', 'Maestria'), ('Doctorado', 'Doctorado'), ('Diplomado', 'Diplomado'), ('Curso', 'Curso'), ('Certificacion', 'Certificacion'), ('Otro', 'Otro')], default='sin especificar', max_length=20),
        ),
        migrations.AlterField(
            model_name='infopesonalmodel',
            name='gender',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro'), ('Sin especificar', 'Sin especificar')], default='sin especificar', max_length=20),
        ),
        migrations.AlterField(
            model_name='infopesonalmodel',
            name='marital_status',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Otro', 'Otro'), ('Sin especificar', 'Sin especificar')], default='sin especificar', max_length=20),
        ),
        migrations.AlterField(
            model_name='interesmodel',
            name='area_interes',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Ventas', 'Ventas'), ('Humanidades', 'Humanidades'), ('Administración', 'Administración'), ('Industria', 'Industria'), ('Analisis de Datos', 'Analisis de Datos'), ('Tecnología', 'Tecnología'), ('Desarrollo de software', 'Desarrollo de Software'), ('Ciencias Exactas', 'Ciencias Exactas')], max_length=100),
        ),
        migrations.AlterField(
            model_name='interesmodel',
            name='experiencia_interes',
            field=models.CharField(choices=[('Becario', 'Becario'), ('Primer Empleo', 'Primer Empleo'), ('Poca Experiencia', 'Poca Experiencia'), ('Experiencia Media', 'Experiencia Media'), ('Mucha experiencia', 'Mucha Experiencia'), ('Cargos ejecutivos', 'Cargos ejecutivos')], max_length=100),
        ),
        migrations.AlterField(
            model_name='interesmodel',
            name='modalidad',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Hibrido', 'Hibrido'), ('Sin especificar', 'Sin especificar')], max_length=30),
        ),
        migrations.AlterField(
            model_name='interesmodel',
            name='tipo_trabajo',
            field=models.CharField(choices=[('Tiempo Completo', 'Tiempo Completo'), ('Medio Tiempo', 'Medio Tiempo'), ('Proyecto', 'Proyecto'), ('Sin especificar', 'Sin especificar')], max_length=30),
        ),
    ]
