# Generated by Django 4.0.3 on 2022-05-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopesonalmodel',
            name='date_birth',
            field=models.DateTimeField(default='2018-06-29'),
        ),
    ]
