# Generated by Django 4.0.3 on 2022-07-01 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitantes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoacademicamodel',
            name='estatus_academico',
            field=models.CharField(choices=[('FINALIZADO', 'FINALIZADO'), ('EN CURSO', 'EN CURSO'), ('TRUNCO', 'TRUNCO'), ('OTRO', 'OTRO')], default='sin especificar', max_length=20),
        ),
        migrations.AlterField(
            model_name='infoacademicamodel',
            name='nivel_escolar',
            field=models.CharField(choices=[('CARRERA TECNICA', 'CARRERA TECNICA'), ('UNIVERSIDAD', 'UNIVERSIDAD'), ('MAESTRIA', 'MAESTRIA'), ('DOCTORADO', 'DOCTORADO'), ('DIPLOMADO', 'DIPLOMADO'), ('CURSO', 'CURSO'), ('CERTIFICACION', 'CERTIFICACION'), ('OTRO', 'OTRO')], default='sin especificar', max_length=20),
        ),
        migrations.AlterField(
            model_name='infoacademicamodel',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='infopesonalmodel',
            name='gender',
            field=models.CharField(choices=[('FEMENINO', 'FEMENINO'), ('MASCULINO', 'MASCULINO'), ('OTRO', 'OTRO')], default='sin especificar', max_length=20),
        ),
        migrations.AlterField(
            model_name='infopesonalmodel',
            name='marital_status',
            field=models.CharField(choices=[('SOLTERO', 'SOLTERO'), ('CASADO', 'CASADO'), ('OTRO', 'OTRO')], default='sin especificar', max_length=20),
        ),
        migrations.AlterField(
            model_name='infopesonalmodel',
            name='user_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videosolicitantemodel',
            name='user_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
