# Generated by Django 4.0.3 on 2022-05-31 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitantes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAcademicaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('institucion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(default='0000-00-00', null=True)),
                ('fecha_fin', models.DateField(default='0000-00-00', null=True)),
                ('nivel_escolar', models.CharField(choices=[('Carrera Técnica', 'Carrera Tecnica'), ('Universidad', 'Universidad'), ('Maestría', 'Maestria'), ('Doctorado', 'Doctorado'), ('Curso', 'Curso'), ('Certificación', 'Certificación'), ('Otro', 'Otro'), ('sin especificar', 'Sinespecificar')], default='sin especificar', max_length=20)),
                ('estatus_academico', models.CharField(choices=[('Finalizado', 'Finalizado'), ('En curso', 'En Curso'), ('Trunco', 'Trunco'), ('Otro', 'Otro'), ('sin especificar', 'Sinespecificar')], default='sin especificar', max_length=20)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
