# Generated by Django 4.0.3 on 2022-05-31 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitantes', '0003_infoacademicamodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoacademicamodel',
            old_name='name',
            new_name='nombre',
        ),
    ]
