# Generated by Django 4.0.3 on 2022-05-31 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitantes', '0004_rename_name_infoacademicamodel_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoacademicamodel',
            old_name='nombre',
            new_name='name',
        ),
    ]
