# Generated by Django 4.0.3 on 2022-05-11 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopersonal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopesonalmodel',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
