# Generated by Django 4.0.3 on 2022-05-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopersonal', '0003_infopesonalmodel_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSolicitanteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='infopesonalmodel',
            name='video',
        ),
    ]
